local source=assert(arg[1])
local heavy=assert(loadfile(source..'/heavy.lua'))()
local data=assert(loadfile(source..'/heavy_data.lua'))()
local function got(tags,difficulty,complete)
    return table.concat(heavy.possible({faction=2,tags=tags,difficulty=difficulty,complete=complete},data),',')
end
assert(got({1},10,true)=='Bile Titans')
assert(got({6},9,true)=='Bile Titans')
assert(got({1,11},10,true)=='Dragonroaches')
assert(got({1},10,false)=='')
assert(got({1},1,true)=='')
assert(got({1,9},10,true)=='Gloom Bile Titans')
print('PASS: difficulty gates, Titan versus Dragon replacement, Gloom replacement and incomplete-data suppression')
