-- Plain ASCII player-facing descriptions. These describe composition traits.
-- They are not an exhaustive roster or a promise of individual encounters.
return {
    [1] = {'BILE BUGS', 'Bile Spewers, Spitters, Bile Warriors'},
    [2] = {'ARMORED BUGS', 'Hive Guards and Charger groups'},
    [3] = {'HUNTER SWARMS', 'Hunters and Pouncers'},
    [4] = {'FLYER COMPOSITION', 'Unit intelligence unavailable'},
    [5] = {'LIGHT BUGS', 'Scavengers, Warriors, Brood Commanders'},
    [6] = {'BUG NURSERY', 'Nursing Spewers and Scavenger groups'},
    [7] = {'MIXED TERMINIDS', 'Mixed ground forces'},
    [8] = {'SUPER PREDATORS', 'Enhanced Hunter variants'},
    [9] = {'GLOOM VARIANTS', 'Gloom Warriors, Hunters and Titans'},
    [10] = {'BURROWERS', 'Burrowing Warriors, Spewers and Chargers'},
    [11] = {'DRAGONROACH ACTIVITY', 'Dragon unit enabled by mission modifier'},
    [12] = {'SHRIEKER MODIFIER', 'Unit intelligence unavailable'},
    [13] = {'ASSAULT FORCES', 'Melee infantry and assault groups'},
    [14] = {'PHALANX FORCES', 'Heavy weapon soldiers and suppressors'},
    [15] = {'ARTILLERY FORCES', 'Rocket soldiers and artillery groups'},
    [16] = {'AIR COMPOSITION', 'Unit intelligence unavailable'},
    [17] = {'ARMORED COLUMN', 'Scout walkers and tank groups'},
    [18] = {'MIXED AUTOMATONS', 'Mixed infantry and armored forces'},
    [19] = {'JUMP ASSAULT', 'Jump infantry and jump soldiers'},
    [20] = {'CYBORG FORCES', 'Cyborg elites and siege engines'},
    [21] = {'GUNSHIP MODIFIER', 'Unit intelligence unavailable'},
    [22] = {'IVORY LEGION', 'Flamer infantry and shotgun soldiers'},
    [23] = {'HIVE LORD MODIFIER', 'Unit intelligence unavailable'},
    [24] = {'ILLUMINATE STRAGGLERS', 'Unit intelligence unavailable'},
    [25] = {'WAR MACHINE MODIFIER', 'Unit intelligence unavailable'},
    [26] = {'ILLUMINATE ENGINEERS', 'Staff units, jet units and exomechs'},
    [27] = {'ILLUMINATE INVASION', 'Corrupted, Overseers and tripods'},
    [28] = {'ILLUMINATE HARVEST', 'Corrupted, beam units and tripods'},
    [29] = {'BODY HORROR', 'Corrupted and body horror variants'},
    [30] = {'SEAF SUPPORT', 'Allied soldiers and specialists'},
}
